### ISSUE TITLE
关于发送失败的问题

### ISSUE THREAD

**Issue by yuyue31** [ningbodong/ExcelRemainder#1]
我看了一下好像是因为没有通过企业微信的企业可信ip，不知道是否是这个原因，请大佬看一下
![image](https://github.com/ningbodong/ExcelRemainder/assets/106214532/faa85f5e-720d-4eab-9c66-70b387b98411)

**Comment by ningbodong** [comment]
这个post接口跟IP没太大关系，大概率是你填的参数有误。请检查这几个API参数是否正确？
corpid = 'wwxxxxxxxxxx' //企业ID
corpsecret = '4xxxxxxxx'  //企业密钥
agentid = 'xxxxx'  //应用ID
touser = 'xxxx'  // @all或者用户ID

你可以在浏览器直接执行带参数的url看看结果，
https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid={corpid}&corpsecret={corpsecret}

如：https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=ww73d9xxxxxx7&corpsecret=wKb_Yh50vNxxxxxxxxxxxxxxxxxxyg#/

**Comment by yuyue31** [comment]
已查明原因，是企业ip不在白名单，导致报600020错误，现已解决，感谢大佬。曾在前几天转给大佬50喝咖啡，再次感谢大佬的源码！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 下午2:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ningbodong/ExcelRemainder] 关于发送失败的问题 (Issue #1)




 
这个post接口跟IP没太大关系，大概率是你填的参数有误。请检查这几个API参数是否正确？
 corpid = 'wwxxxxxxxxxx' //企业ID
 corpsecret = '4xxxxxxxx'  //企业密钥
 agentid = 'xxxxx'  //应用ID
 touser = 'xxxx'  // @ALL或者用户ID
 
你可以在浏览器直接执行带参数的url看看结果，
 https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid={corpid}&amp;corpsecret={corpsecret}
 
如：https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=ww73d9xxxxxx7&amp;corpsecret=wKb_Yh50vNxxxxxxxxxxxxxxxxxxyg#/
